/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aff7b461-c6c4-4eea-95e7-7821c34efefb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6zKKtnJnu",
    "aws_user_pools_web_client_id": "5ogfq7jm1menok06dnrcbocu26",
    "oauth": {
        "domain": "amplifyapp07dd0e1a-07dd0e1a-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://ovqafelb5vagrdktlputfnunf4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r246x277undzxfthh4zls3d2ke"
};


export default awsmobile;
